#+TITLE: Niluje's Doom Emacs configuration
#+AUTHOR: Niluje
#+OPTIONS: num:nil
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup


* Doom emacs literate configuration

** Host dependant configuration

Some settings need to be adjusted according to where we are (@work, @home).
Rely on hostname to make the choice.

Setting the projectile project path speeds up the launching time by 20 on
the @work configuration where the filesystem is very slow.

#+begin_src elisp
(if (string= "blupblup" (system-name))
    (setq user-full-name "cdebarge"
	  user-mail-address "cdebarge@nanoxplore.com"
	  org-directory "~/Work/org"
	  projectile-project-search-path '("~/Work/SVN_HOME"))
    (setq user-full-name "Niluje"
	  user-mail-address "debarge.cedric@nanoxplore.com"
	  org-directory "~/Work_local/org"
	  projectile-project-search-path '("~/Work_local")))
#+end_src


** UI

*** Theme

Use Gruvbox because Solarized is just a desaster on emacs
#+begin_src elisp
(setq doom-theme 'doom-gruvbox)
#+end_src

*** UI basic elements

Show the menu bar because I am an Emacs beginner and I need backup
#+begin_src elisp
(menu-bar-mode 1)
#+end_src

Display line number in relative form. Just disable this if Emacs becomes too slow
#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src

Activates the rainbow delimiters for prog modes only
#+begin_src elisp
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
#+end_src

Highlight whitespaces and anything beyond 80th column for prog modes only
#+begin_src elisp
(use-package! whitespace
  :config
  (setq
    whitespace-style '(face tabs tab-mark spaces space-mark trailing
lines-tail newline newline-mark)
    whitespace-display-mappings '(
      (space-mark   ?\     [?\u00B7]     [?.])
      (space-mark   ?\xA0  [?\u00A4]     [?_])
      (newline-mark ?\n    [?¬ ?\n])
      (tab-mark     ?\t    [?\u00BB ?\t] [?\\ ?\t]))))

(add-hook 'prog-mode-hook (global-whitespace-mode +1))
#+end_src

*** Window spliting stuff

Horizontal split on SPC w -
#+begin_src elisp
(map! :leader
      :nv "w -" nil
      :desc "Horizontal split"
      :n "w -" 'evil-window-split)
#+end_src

Vertical split on SPC w /
#+begin_src elisp
(map! :leader
      :nv "w /" nil
      :desc "Vertical split"
      :n "w /" 'evil-window-vsplit)
#+end_src

*** Treemacs

Remap opening the sidebar on SPC f t (spaceneovim style!).
Also on SPC o n
#+begin_src elisp
(map! :leader
      :nv "o n" nil
      :desc "Open treemacs pane"
      :n "o n" #'+treemacs/toggle)
(map! :leader
      :nv "f t" nil
      :desc "Open treemacs pane"
      :n "f t" #'+treemacs/toggle)
#+end_src

*** Copy / Paste buffer stuff

Just a foolish attempt to handle copy and paste in the least undesirable way
#+begin_src elisp
(when (> (display-color-cells) 16)         ;if not in CLI
  (setq x-select-enable-clipboard t
        interprogram-paste-function
        'x-cut-buffer-or-selection-value))
#+end_src

Delete selection if text is inserted (Windows left-over from my past days)
#+begin_src elisp
(delete-selection-mode 1)
#+end_src


** Language specific section

*** Verilog

See with RTL masters for more efficient settings.
Keep a basic TAB, 2 chars for the moment.
#+begin_src elisp
(custom-set-variables
 '(verilog-align-ifelse t)
 '(verilog-auto-lineup (quote all))
 '(verilog-auto-newline nil)
 '(verilog-case-indent 2)
 '(verilog-cexp-indent 2)
 '(verilog-highlight-grouping-keywords t)
 '(verilog-highlight-modules t)
 '(verilog-indent-level 2)
 '(verilog-indent-level-behavioral 2)
 '(verilog-indent-level-declaration 2)
 '(verilog-indent-level-module 2)
 '(verilog-tab-to-comment t))

(add-hook 'verilog-mode-hook
  (function (lambda ()
          (setq evil-shift-width 2))))
#+end_src

*** VHDL

Same as Verilog.
See with RTL masters for more efficient settings.
Keep a basic TAB, 2 chars for the moment.
#+begin_src elisp
(setq vhdl-basic-offset 2)
(setq vhdl-indent-tabs-mode t)
#+end_src

*** C

The big mess.
Always uses Linux style. But creates commands to easily switch from:
- Linux style: 8 char per tabs --> niluje/setup-c-indent-linux-style
- Niluje style: 4 char per tabs --> niluje/setup-c-indent-niluje-style

Bonus: uses norl python script (located in .doom.d/tools) at each c file
opening to guess between each style. Default is Niluje style.

**** Commands to apply wanted style

#+begin_src elisp
(defun niluje/setup-c-indent (n)
  "Sets c indent style for this buffer"
  (c-set-style "Linux")
  (setq c-basic-offset n
        c-indent-level n
        indent-tabs-mode t)
  (doom/set-indent-width n)
  )

(defun niluje/setup-c-indent-niluje-style ()
  "Sets c indent to niluje style (Linux + 4 spaces)"
  (interactive)
  (niluje/setup-c-indent 4)
  )

(defun niluje/setup-c-indent-linux-style ()
  "Sets c indent to linux style"
  (interactive)
  (niluje/setup-c-indent 8)
  )
#+end_src

**** Style guessing system

#+begin_src elisp
(defun niluje/c-indent-guess ()
  "Guesses between 8 char per tab and 4 char per tab within Linux style"
  (interactive)
  (setq norl-path "~/.doom.d/tools/norl")
  (setq norl-cmd (concat norl-path " " buffer-file-name " 2>/dev/null"))
  (setq norl-ret (shell-command-to-string norl-cmd))
  (setq guessed-indent-style (replace-regexp-in-string "\r?\n\\'" "" norl-ret))
  (if (string-prefix-p "linux" guessed-indent-style)
       (niluje/setup-c-indent-linux-style)
       (niluje/setup-c-indent-niluje-style))
  )

(add-hook 'c-mode-hook 'niluje/c-indent-guess)
#+end_src

*** ORG MODE

Uses TODO handling similar to Spacemacs: cycling instead of popup menu.
#+begin_src elisp
(after! evil-org
  (evil-org-set-key-theme '(textobjects insert navigation additional shift todo heading))
)
(setq org-use-fast-todo-selection nil)
#+end_src

Always add closing timestamp to tasks
#+begin_src elisp
(setq org-log-done 'time)
#+end_src
